// All core UI strings, centralized as plain English constants.
// Extension point for future i18n of the chrome (principle 7) — pedagogical
// content (titles, labels, notes) never lives here: it belongs to manifests.
export const STR = {
  APP_NAME: 'ENIB Lab',
  SEARCH: 'Search experiments',
  SEARCH_PLACEHOLDER: 'Type to search experiments…',
  NO_RESULTS: 'No matching experiment',
  PARAMETERS: 'Parameters',
  SCENE: 'Scene',
  NO_SCENES: 'No scenes',
  ACTION_DRAW: 'Draw',
  ACTION_RESET: 'Reset',
  ACTION_REVEAL: 'Reveal',
  COPY_LINK: 'Copy link',
  COPIED: 'Copied!',
  PRESENTATION: 'Presentation mode',
  THEME: 'Theme',
  TEACHER_MODE: 'Teacher Mode',
  INSPECTOR: 'Inspector',
  OBSERVABLES: 'Observables',
  DOWNLOAD: 'Download',
  EXPORT_SVG: 'SVG',
  EXPORT_PNG: 'PNG',
  COPY_PNG: 'Copy',
  COMPUTING: 'computing…',
  COMPUTE_ABORTED: '⚠ Computation aborted — values too large',
  COMPUTE_ERROR: '⚠ Computation error',
  SEED: 'Seed',
  DERIVED: 'Derived',
  CLOSE: 'Close',
  MASKED_HINT: 'Hidden parameter — use Reveal to unveil',
  COLLAPSE_SIDEBAR: 'Toggle sidebar',
};
